// "use client";
//서버 컴포넌트
import "./globals.css";
import Link from "next/link";
import { Control } from "./Control";
// import { useEffect, useState } from "react";
export const metadata = {
  title: "Web tutorial",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const [topics, setTopics] = useState([]);
  const res = await fetch(process.env.NEXT_PUBLIC_URL + "topics", {
    next: { revalidate: 0 },
    //{cache: 'no-store'}
    //nextJS는 자동 캐시를 지원. 이를 옵션으로 없앨 수 있다.
  });
  const topics = await res.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
